version: '3.3'
services:
  postgres:
    image: postgres
    container_name: 'postgresql'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    restart: always
